/*
    This file is a part of Tiny-Shading-Language or TSL, an open-source cross
    platform programming shading language.

    Copyright (c) 2020-2020 by Jiayin Cao - All rights reserved.

    TSL is a free software written for educational purpose. Anyone can distribute
    or modify it under the the terms of the GNU General Public License Version 3 as
    published by the Free Software Foundation. However, there is NO warranty that
    all components are functional in a perfect manner. Without even the implied
    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
    General Public License for more details.

    You should have received a copy of the GNU General Public License along with
    this program. If not, see <http://www.gnu.org/licenses/gpl-3.0.html>.
 */


/*
    --------------------------------------------------------------------
    WARNING:
            This file is automatically generated, do not modify.
    --------------------------------------------------------------------
*/

#pragma once

// Version of tiny-shading-language:
#define _VERSION_MAJOR        0
#define _VERSION_MINOR        0
#define _VERSION_PATCH        0
#define _VERSION              ( 65536 * _VERSION_MAJOR + 256 * _VERSION_MINOR + _VERSION_PATCH )

#define Tsl_Namespace                    Tsl_Namespace_0_0_0

#define TSL_NAMESPACE_BEGIN              namespace Tsl_Namespace{
#define TSL_NAMESPACE_END                }
#define USE_TSL_NAMESPACE                using namespace Tsl_Namespace;

// This will generate something like "TinyShadingLanguage 1.2.3"
#define TSL_MAKE_VERSION_STRING2(a,b,c) #a "." #b "." #c
#define TSL_MAKE_VERSION_STRING(a,b,c) TSL_MAKE_VERSION_STRING2(a,b,c)
#define TSL_LIBRARY_VERSION_STRING TSL_MAKE_VERSION_STRING(_VERSION_MAJOR, _VERSION_MINOR, _VERSION_PATCH )
#define TSL_INTRO_STRING "TinyShadingLanguage " TSL_LIBRARY_VERSION_STRING

// This is just a hack to make sure the namespace is always valid
TSL_NAMESPACE_BEGIN
TSL_NAMESPACE_END
