name: Build TSL

on: [push, pull_request]

jobs:
  Windows:
    runs-on: windows-latest
    steps:
    - name: Checking Out Source Code
      uses: actions/checkout@v1
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Get Cache Directory
      id: cache-dir
      run: |
           echo ::set-output name=dir::%CD%
      shell: cmd
    - name: Load Dependencies from Cache
      uses: actions/cache@v1
      id: cache-dep
      with:
        path: ${{ steps.cache-dir.outputs.dir }}/dependencies
        key: Windows-dep-ver-2
    - name: Install Dependencies
      if: steps.cache-dep.outputs.cache-hit != 'true'
      run: make update_dep
      shell: cmd
    - name: Build Release Version
      run: make
      shell: cmd
    - name: Build Debug Version
      run: make debug
      shell: cmd
    - name: Unit test
      run: make test
      shell: cmd
  Macos:
    runs-on: macOS-latest
    steps:
    - name: Checking Out Source Code
      uses: actions/checkout@v1
    - name: Configure Environment
      run: |
           brew install flex
           brew install bison
    - name: Get Cache Directory
      id: cache-dir
      run: |
           echo "::set-output name=dir::$(pwd)"
    - name: Load Dependencies from Cache
      uses: actions/cache@v1
      id: cache-dep
      with:
        path: ${{ steps.cache-dir.outputs.dir }}/dependencies
        key: MacOS-dep-ver-2
    - name: Install Dependencies
      if: steps.cache-dep.outputs.cache-hit != 'true'
      run: make update_dep
    - name: Build Release Version
      run: |
           echo 'export PATH="/usr/local/opt/bison/bin:$PATH"' >> ~/.bash_profile
           source ~/.bash_profile
           bison -V
           make
    - name: Build Debug Version
      run: |
           echo 'export PATH="/usr/local/opt/bison/bin:$PATH"' >> ~/.bash_profile
           source ~/.bash_profile
           bison -V
           make debug
    - name: Unit test
      run: make test
  Ubuntu_18_04:
    runs-on: ubuntu-18.04
    steps:
    - name: Checking Out Source Code
      uses: actions/checkout@v1
    - name: Configure Environment
      run: |
           sudo apt-get install flex
           sudo apt-get install bison
    - name: Get Cache Directory
      id: cache-dir
      run: |
           echo "::set-output name=dir::$(pwd)"
    - name: Load Dependencies from Cache
      uses: actions/cache@v1
      id: cache-dep
      with:
        path: ${{ steps.cache-dir.outputs.dir }}/dependencies
        key: MacOS-dep-ver-2
    - name: Install Dependencies
      if: steps.cache-dep.outputs.cache-hit != 'true'
      run: make update_dep
    - name: Build Release Version
      run: make
    - name: Build Debug Version
      run: make debug
    - name: Unit test
      run: make test
  Ubuntu_16_04:
    runs-on: ubuntu-16.04
    steps:
    - name: Checking Out Source Code
      uses: actions/checkout@v1
    - name: Configure Environment
      run: |
           sudo apt-get install flex
           sudo apt-get install bison
    - name: Get Cache Directory
      id: cache-dir
      run: |
           echo "::set-output name=dir::$(pwd)"
    - name: Load Dependencies from Cache
      uses: actions/cache@v1
      id: cache-dep
      with:
        path: ${{ steps.cache-dir.outputs.dir }}/dependencies
        key: MacOS-dep-ver-0
    - name: Install Dependencies
      if: steps.cache-dep.outputs.cache-hit != 'true'
      run: make update_dep
    - name: Build Release Version
      run: make
    - name: Build Debug Version
      run: make debug
    - name: Unit test
      run: make test
